#!/bin/bash
# sync.sh - Generate tool-specific config files from .skills/ source
# Usage: bash .skills/sync.sh
# Idempotent: safe to run multiple times, same output each time

set -e

SKILLS_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SKILLS_DIR")"

HEADER="<!-- AUTO-GENERATED by .skills/sync.sh - DO NOT EDIT DIRECTLY -->"

echo "Syncing .skills/ → tool configs..."

# ─── 1. Generate .cursor/rules/skills.mdc ───

mkdir -p "$PROJECT_ROOT/.cursor/rules"

cat > "$PROJECT_ROOT/.cursor/rules/skills.mdc" << 'CURSOR_EOF'
---
description: "Project UI primitives and React best practices"
globs: ["src/**/*.tsx", "src/**/*.ts"]
alwaysApply: true
---

<!-- AUTO-GENERATED by .skills/sync.sh - DO NOT EDIT DIRECTLY -->

# UI Primitives (CRITICAL)

CURSOR_EOF

# Inline the ui-primitives SKILL.md content (skip frontmatter and first H1 heading)
sed -n '/^---$/,/^---$/!p' "$SKILLS_DIR/ui-primitives/SKILL.md" | sed '/^# /d' | sed '1{/^$/d;}' >> "$PROJECT_ROOT/.cursor/rules/skills.mdc"

cat >> "$PROJECT_ROOT/.cursor/rules/skills.mdc" << 'CURSOR_REFS'

# React Best Practices

Comprehensive performance optimization guide for React and Next.js (58 rules across 8 categories).

Read individual rules: `.skills/react-best-practices/rules/<rule>.md`

Categories: async (waterfalls), bundle (size), server (SSR), client (data fetching), rendering (paint), rerender (React updates), js (vanilla perf), advanced (patterns).

# Composition Patterns

React composition patterns for building flexible, maintainable components (8 rules).

Read individual rules: `.skills/composition-patterns/rules/<rule>.md`

Categories: architecture, patterns, state, react19.

# Web Design Guidelines

Review UI code for accessibility and UX compliance.

Read: `.skills/web-design-guidelines/SKILL.md`
CURSOR_REFS

echo "  ✓ .cursor/rules/skills.mdc"

# ─── 2. Generate .github/copilot-instructions.md ───

mkdir -p "$PROJECT_ROOT/.github"

{
  echo "$HEADER"
  echo ""
  echo "# Project Coding Instructions"
  echo ""
  echo "## UI Components"
  echo ""
  # Inline ui-primitives content (skip frontmatter and first H1 heading)
  sed -n '/^---$/,/^---$/!p' "$SKILLS_DIR/ui-primitives/SKILL.md" | sed '/^# /d' | sed '1{/^$/d;}'
  echo ""
  echo "## React Best Practices"
  echo ""
  echo "Performance optimization guide for React and Next.js (58 rules)."
  echo ""
  echo "| Priority | Category | Impact | Prefix |"
  echo "|----------|----------|--------|--------|"
  echo "| 1 | Eliminating Waterfalls | CRITICAL | \`async-\` |"
  echo "| 2 | Bundle Size Optimization | CRITICAL | \`bundle-\` |"
  echo "| 3 | Server-Side Performance | HIGH | \`server-\` |"
  echo "| 4 | Client-Side Data Fetching | MEDIUM-HIGH | \`client-\` |"
  echo "| 5 | Rendering Optimization | MEDIUM | \`rendering-\` |"
  echo "| 6 | Preventing Re-renders | MEDIUM | \`rerender-\` |"
  echo "| 7 | Vanilla JS Performance | LOW-MEDIUM | \`js-\` |"
  echo "| 8 | Advanced Patterns | LOW | \`advanced-\` |"
  echo ""
  echo "## Composition Patterns"
  echo ""
  echo "React composition patterns for flexible, maintainable components (8 rules):"
  echo "- Avoid boolean prop proliferation"
  echo "- Use compound components"
  echo "- Lift state appropriately"
  echo "- Prefer children over render props"
  echo "- Use explicit variants over boolean props"
  echo "- Decouple state implementation from interface"
  echo "- React 19: No forwardRef needed"
  echo ""
  echo "## Web Design Guidelines"
  echo ""
  echo "Review UI code for Web Interface Guidelines compliance."
  echo "Check accessibility, design consistency, and UX best practices."
} > "$PROJECT_ROOT/.github/copilot-instructions.md"

COPILOT_LINES=$(wc -l < "$PROJECT_ROOT/.github/copilot-instructions.md")
echo "  ✓ .github/copilot-instructions.md ($COPILOT_LINES lines)"

if [ "$COPILOT_LINES" -gt 500 ]; then
  echo "  ⚠ WARNING: copilot-instructions.md exceeds 500 lines ($COPILOT_LINES)"
fi

# ─── 3. Verify CLAUDE.md has .skills/ reference ───

if grep -q "## Skills" "$PROJECT_ROOT/CLAUDE.md" 2>/dev/null; then
  echo "  ✓ CLAUDE.md already has Skills section"
else
  echo "  ⚠ CLAUDE.md missing Skills section - add manually"
fi

echo ""
echo "Sync complete."
